#!/usr/bin/python

import cgi
import html
import sys
import traceback

print('Content-Type: text/html\n\n')

try:
  import nobjedit

  form = cgi.FieldStorage()

  print(nobjedit.page(form))
except: 
  print("There has been an error. Please cut and paste this error information")
  print("in an email to andrew@longtable.org.<p>\n<p>\n")
  e = traceback.format_exception(sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2])
  for l in e:
    print((html.escape(l) + '<p>').replace('\n', '<br>'))
